### ISSUE TITLE
launch Crash with ACE (Acro's Classical Elements) in my modpack. Sent me here.

### ISSUE THREAD

**Issue by netcore10** [cc-tweaked/cc-restitched#101]
## Useful information to include:
 - Minecraft version 1.18.2
 - CC: Restitched version 1.100.5
 - Logs: 
[crash-2022-05-26_20.36.06-client.txt](https://github.com/cc-tweaked/cc-restitched/files/8787723/crash-2022-05-26_20.36.06-client.txt)
didn't load up long enough for a latest.log
  - Please send `latest.log` AND the appropriate crashlog,
 - Detailed reproduction steps: Not quite sure

**Comment by Merith-TK** [comment]
can you try with `Not Enough Crashes` AND the lastest version of CC:R? 1.100.6

it looks like something in the modpack is trying to register an turtle peripheral, and failing badly

**Comment by netcore10** [comment]
it didn't get to the loading screen
[crash.txt](https://github.com/cc-tweaked/cc-restitched/files/8789427/crash.txt)

**Comment by Merith-TK** [comment]
if you use https://polymc.org for your launcher, it will generate an log that can then be uploaded through an button

can you test with just CC:R and ACE? (plus fabric api) I just tested with latest versions of all and have had no issues, 

please send the `latest.log`, because if it is registering that type of error, then an latest.log has indeed been generated

**Comment by Merith-TK** [comment]
also it appears you didnt do some basic steps for testing if an specific mod caused an crash, I just tested ACE and CC:R together, no crash, so it is another mod in your modpack, 

please send the latest `latest.log` you have availiable using https://mclo.gs

**Comment by netcore10** [comment]
Then it's probably something to do with a mod conflict. I'm probably back at square one on trying to figure out which one it is.

**Comment by netcore10** [comment]
Regardless, it's obviously not CC. for my sanity, Here's the logs of my modpack with polymc. Can you discern what might be the problem?
[latest.log](https://github.com/cc-tweaked/cc-restitched/files/8789799/latest.log)
[crash-2022-05-27_22.24.04-server.txt](https://github.com/cc-tweaked/cc-restitched/files/8789803/crash-2022-05-27_22.24.04-server.txt)
[crash-2022-05-27_22.24.07-client.txt](https://github.com/cc-tweaked/cc-restitched/files/8789804/crash-2022-05-27_22.24.07-client.txt)

for me, it only mentions CC as a potential problem.

**Comment by Merith-TK** [comment]
please upload to https://mclo.gs so I dont have to download them, 

there is an *reason* I say to do this as it color codes the logs so anyone can read them easily

**Comment by netcore10** [comment]
latest log: https://mclo.gs/PerHJsU
Server crash: https://mclo.gs/gDD8scR
client crash: https://mclo.gs/sROMq05

**Comment by Merith-TK** [comment]
now look at latest.log on the website, see how at the top it gives you an rundown of the MC environment?

it also says that an mod as thrown an error

**Comment by netcore10** [comment]
Oh, that's handy. So it suspects alloy forgery?

**Comment by netcore10** [comment]
thanks for the help.

**Comment by Merith-TK** [comment]
yep! it even links you (on the right side of that message) to where alloy forgery threw an error, 
line 1063
https://mclo.gs/PerHJsU#L1063

**Comment by Merith-TK** [comment]
it also censors information it considers private (such as your windows username) so it helps with privacy!

**Comment by netcore10** [comment]
WOW that site is handy.

**Comment by netcore10** [comment]
This makes my headache so much less.

**Comment by toad-dev** [comment]
Here's what I've gathered from reading through the logs:

1. The server crashes because of a mixin transformation error. [The mixin in question is from the mod Arcanus](https://github.com/CammiePone/Arcanus/blob/1.18-dev/src/main/java/dev/cammiescorner/arcanus/core/mixin/client/ClientPlayNetworkHandlerMixin.java).
2. Alloy Forgery gets blamed for the server crash because they're at the base of the stack trace. Their main class's static initializer sets up some sort of particle system library that touches the mixin's target class.
3. CC: Resitched manages to cause a client crash because the server crash prevented our initialization from completing and we assume elsewhere in the code that it always will. We could fix this just so we're not blamed for future unrelated crashes.

I don't know why Arcanus's mixin is failing. I'd file an issue over there so they can look into it.

**Comment by netcore10** [comment]
Sadly arcanus isn't being updated, it's why i tried to test out ace before i commit to swapping.

**Comment by netcore10** [comment]
I should probably just remove arcanus.
