### ISSUE TITLE
Crash when turtle moves

### ISSUE THREAD

**Issue by Szprinktrap** [cc-tweaked/cc-restitched#61]
I saw that this was a issue before, but it appears that it still happens.
Basically when i placed a turtle on my server and ran the "dance" program, the server crashed.
Same thing also happens on singleplayer.

Crash logs attached.
[crash-2022-02-21_14.35.34-server.txt](https://github.com/cc-tweaked/cc-restitched/files/8109666/crash-2022-02-21_14.35.34-server.txt)
[crash-2022-02-21_14.40.25-server.txt](https://github.com/cc-tweaked/cc-restitched/files/8109669/crash-2022-02-21_14.40.25-server.txt)

## Useful information to include:
 - Minecraft version: 1.18.1
 - CC: Restitched version: 1.100.1
 - Logs: attached on top
 - Detailed reproduction steps: Place a turtle and make it move somehow.

**Comment by Merith-TK** [comment]
Please send the `latest.log` file for these crashes, 
We need latest.log because it contains *everything*, what mods your using, if you have any other mods causing errors before the crash, etc

from that crash it looks like a mod that we *know* causes issues and they refuse to fix it, 

also please retest with latest github actions release on the 1.18/stable branch

**Comment by Szprinktrap** [comment]
Alright, here's the latest.log:
[latest.log](https://github.com/cc-tweaked/cc-restitched/files/8120662/latest.log)

Retested with latest GH Actions release and it looks like it works fine.

**Comment by Merith-TK** [comment]
yep, look at #53

**Comment by Merith-TK** [comment]
should be fixed in latest release! go ahead and test!
