### ISSUE TITLE
Better End Music Discs and CC:Restitched

### ISSUE THREAD

**Issue by CastilloAnthony** [cc-tweaked/cc-restitched#89]
Hello, I am currently playing in a minecraft 1.18.1 Fabric modpack with 100+ mods including cc-restitched-1.100.3.

One of the mods in the modpack adds music discs, that is the Better End mod (located here: https://www.curseforge.com/minecraft/mc-mods/betterend). I've been having some troubles playing these music discs from the mod in CC:Restitched Disk Drives. The Drives can read the titles of the discs and "play" the discs, but there is no audio when they're being played. I've tried playing the disc in a jukebox and it works perfectly fine. Its just that when it gets "played" in the CC:Restitched disk drive that it has no audio. Other music discs from other mods like Anchor and Actually Additions work as you'd expect.

**Comment by Merith-TK** [comment]
I hate to say it, but as an modded server owner,

Better End is just cursed, and they don't want to fix it because it "works", they have so much buggy code that I have basically given up running it on my servers and modpacks. It's an great mod but with too many issues when used with other mods. 

I would suggest opening an issue on their github and then reference this one. As sadly this is something we won't prioritize unless someone decides to make an fix for it.
